import Head from 'next/head';
import Modal from './Modal';
import Sidebar from './Sidebar';
import HomePage from './Home';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Sidebar & Modal</title>
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <HomePage />
            </main>

            <Modal />

            <Sidebar />
        </div>
    );
}
