import Head from 'next/head';
import React, { useState, useEffect } from 'react';
import { FaAngleDoubleRight } from 'react-icons/fa';

/* A variable that is storing the url of the api we are using. */
const url = 'https://course-api.com/react-tabs-project';

/**
 * We're using the useState hook to set the initial state of the loading variable to true, and the jobs
 * variable to an empty array. We're then using the useEffect hook to fetch the jobs data from the API
 * and set the jobs variable to the data we get back. We're also setting the loading variable to false
 * @returns The return statement is returning the following:
 */
export default function Home() {
    const [loading, setLoading] = useState(true);
    const [jobs, setJobs] = useState([]);
    const [value, setValue] = useState(0);

    /**
     * We're using the fetch API to make a request to the url we defined earlier, and then we're using
     * the setJobs function to update the jobs state with the new jobs we get back from the API
     */
    const fetchJobs = async () => {
        const response = await fetch(url);
        const newJobs = await response.json();
        setJobs(newJobs);
        setLoading(false);
    };

    /* It's calling the fetchJobs function when the component mounts. */
    useEffect(() => {
        fetchJobs();
    }, []);

    /* It's checking if the loading state is true, and if it is, it's returning a loading message. */
    if (loading) {
        return (
            <section className="section loading">
                <h1>loading...</h1>
            </section>
        );
    }

    const { company, dates, duties, title } = jobs[value];

    return (
        <div>
            <Head>
                <title>Tabs Demo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <section className="section">
                    <div className="title">
                        <h2>experience</h2>
                        <div className="underline"></div>
                    </div>
                    <div className="jobs-center">
                        {/* btn container */}
                        {/* It's mapping over the jobs array and returning a button for each job. */}
                        <div className="btn-container">
                            {jobs?.map((item, index) => {
                                return (
                                    <button
                                        className={`job-btn ${
                                            index === value && 'active-btn'
                                        }`}
                                        key={item.id}
                                        onClick={() => setValue(index)}
                                    >
                                        {item.company}
                                    </button>
                                );
                            })}
                        </div>

                        {/* job info */}
                        {/* It's displaying the job information. */}
                        <article className="job-info">
                            <h3>{title}</h3>
                            <h4>{company}</h4>
                            <p className="jobs-date">{dates}</p>
                            {duties?.map((duty, index) => {
                                return (
                                    <div className="job-desc" key={index}>
                                        <FaAngleDoubleRight className="job-icon" />
                                        <p>{duty}</p>
                                    </div>
                                );
                            })}
                        </article>
                    </div>
                </section>
            </main>

            <footer></footer>
        </div>
    );
}
