import Head from 'next/head';
import React, { useState } from 'react';
import data from '../data';

export default function Home() {
    const [count, setCount] = useState(0);
    const [text, setText] = useState([]);

    /**
     * It takes the amount of paragraphs the user wants to generate, and then fills an array with the
     * data from the data.js, and then slices the array to the amount of paragraphs the user wants
     * @param e - the event object
     */
    const handleSubmit = (e) => {
        e.preventDefault();
        let amount = parseInt(count);
        if (amount <= 0) {
            amount = 1;
        }
        let textData = new Array(amount).fill(data).flat();
        setText(textData.slice(0, amount));
    };

    return (
        <div>
            <Head>
                <title>Lorem Ipsum Demo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <section className="section-center">
                    <h3>tired of boring lorem ipsum?</h3>
                    <form className="lorem-form" onSubmit={handleSubmit}>
                        <label htmlFor="amount">paragraphs:</label>
                        <input
                            type="number"
                            name="amount"
                            id="amount"
                            value={count}
                            onChange={(e) => setCount(e.target.value)}
                        />
                        <button type="submit" className="btn">
                            generate
                        </button>
                    </form>
                    <article className="lorem-text">
                        {text?.map((item, index) => {
                            return <p key={index}>{item}</p>;
                        })}
                    </article>
                </section>
            </main>
        </div>
    );
}
